#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null && polybar-msg cmd quit 
polybar -r &

# configure cursor
xsetroot -cursor_name left_ptr

# bspc monitor -d 一 二 三
bspc monitor -d I II III

bspc config focused_border_color "#b5bd68"
bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config automatic_scheme     alternate
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# Custom rules
bspc rule -a Nitrogen state=floating
bspc rule -a "jetbrains-idea:*:splash" state=floating
